version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://ms-paciente:8081
      - AUTH_SERVICE_URL=http://ms-autenticacao:8082
      - APPOINTMENT_SERVICE_URL=http://ms-consulta:8083
    depends_on:
      - ms-paciente
      - ms-consulta
      - ms-autenticacao

  ms-paciente:
    build: ./ms-paciente
    container_name: ms-paciente
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-paciente:5432/sgh-users
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db-paciente

  db-paciente:
    image: postgres:17
    container_name: db-paciente
    environment:
      POSTGRES_DB: sgh-users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

  ms-consulta:
    build: ./ms-consulta
    container_name: ms-consulta
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-consulta:5432/sgh-consultas
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db-consulta

  db-consulta:
    image: postgres:17
    container_name: db-consulta
    environment:
      POSTGRES_DB: sgh-consultas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"

  ms-autenticacao:
    build: ./ms-autenticacao
    container_name: ms-autenticacao
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-autenticacao:5432/sgh-auth
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db-autenticacao

  db-autenticacao:
    image: postgres:17
    container_name: db-autenticacao
    environment:
      POSTGRES_DB: sgh-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"