version: '3.9'

services:
  db-ms_autenticacao:
    image: postgres:15
    environment:
      POSTGRES_DB: sgh-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - dbdata-ms_autenticacao:/var/lib/postgresql/data

  ms-autenticacao:
    build:
      context: ./ms-autenticacao
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-ms_autenticacao:5432/sgh-auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db-ms_autenticacao

volumes:
  dbdata-ms_autenticacao:
