version: '3.9'

services:
  db-ms_autenticacao:
    image: postgres:15
    environment:
      POSTGRES_DB: sgh-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - dbdata-ms_autenticacao:/var/lib/postgresql/data

  ms-autenticacao:
    build:
      context: ./ms-autenticacao
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-ms_autenticacao:5432/sgh-auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db-ms_autenticacao
      - rabbitmq

  db-ms_paciente:
    image: postgres:15
    environment:
      POSTGRES_DB: sgh-users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - dbdata-ms_paciente:/var/lib/postgresql/data

  ms-paciente:
    build:
      context: ./ms-paciente
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-ms_paciente:5432/sgh-users
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin

      # Configurações da aplicação
      RABBITMQ_EXCHANGE: sgh.exchange
      RABBITMQ_ROUTINGKEY: sgh.usuario.novo
    depends_on:
      - db-ms_paciente
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  dbdata-ms_autenticacao:
  dbdata-ms_paciente:
